"""
Business Domain — Classical Patterns (Layer: Natal Promise / Archetype)

These are natal chart patterns (yogas, house activations, D9 placements) that define
the native's BUSINESS ARCHETYPE. They don't have timing — they describe what kind
of business the native is suited for and what structural strengths/weaknesses exist.

timing_band = "none" → these are promise indicators, not timing triggers.
They modify confidence when dasha/transit/fast_trigger rules fire.

Sources: BPHS, Phaladeepika, Jataka Parijata, Nirayana System
"""

CLASSICAL_PATTERNS = [
    {
        "rule_id": "phaladeepika_speculative_business_5_11",
        "name": "5th-11th Lord Connection — Speculative Business Acumen",
        "description": "The connection between the house of investments/speculation (5th) and the house of gains (11th) creates an archetype suited for speculative markets and investments.",
        "source_text": {
            "work_name": "MANTRESWARA'S PHALA DEEPIKA",
            "chapter": None,
            "verse": "29",
            "page": None,
            "quote": "If the lord of the 11th is posited in the 5th, or the lord of the 5th occupies the 11th, or the lords of the 5th and the 11th are conjoined together... there will be... profit in speculation.",
        },
        "domain": "business",
        "event_family": "speculative_business",
        "event_subtype": ["speculative_business"],
        "rule_type": "classical_pattern",
        "status": "active",
        "priority": 90,
        "polarity": "supportive",
        "timing_band": "none",
        "conditions": {
            "all_of": [],
            "any_of": [
                {"kind": "house_lord_position", "operator": "in", "value": {"lord_of": 11, "in_house": 5}},
                {"kind": "house_lord_position", "operator": "in", "value": {"lord_of": 5, "in_house": 11}},
                {"kind": "planet_conjunction", "operator": "conjunct", "value": {"planets": ["5th_lord", "11th_lord"]}},
            ],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["5", "11"],
            "planets": ["5th_lord", "11th_lord"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.95,
        },
        "interpretation": {
            "meaning": "Symbolic indicator of speculative business acumen. The connection between the house of investments/speculation (5th) and the house of gains (11th) creates an archetype suited for speculative markets and investments.",
            "mode": "speculative_business",
            "quality": "supportive",
            "confidence": 0.90,
        },
        "outputs": {
            "symbolic_label": "speculative_business_archetype",
            "likelihood_band": "high",
            "timing_band": "broad",
            "recommended_action": "leverage_speculative_instinct",
        },
        "notes": "Classical wealth combination highlighting speculative trading.",
    },
    {
        "rule_id": "bphs_satramooladdhana_yoga_2_6",
        "name": "Satramooladdhana Yoga — Wealth Through Conflict/Litigation",
        "description": "2nd lord in 6th with benefic indicates a business archetype where wealth is extracted from conflict, enemies, or litigation.",
        "source_text": {
            "work_name": "Brihat Parashara Hora Shastra",
            "chapter": "24",
            "verse": "18",
            "page": None,
            "quote": "When Dhana's lord is in Ari Bhava along with a benefic, the native will gain wealth through his enemies. It is know as satramooladdhana yoga.",
        },
        "domain": "business",
        "event_family": "profit_growth",
        "event_subtype": ["litigation_prone", "sudden_gains"],
        "rule_type": "yoga",
        "status": "active",
        "priority": 82,
        "polarity": "mixed",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "house_lord_position", "operator": "in", "value": {"lord_of": 2, "in_house": 6}},
                {"kind": "planet_conjunction", "operator": "conjunct", "value": "benefic"},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["2", "6"],
            "planets": ["2nd_lord"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.90,
        },
        "interpretation": {
            "meaning": "Satramooladdhana Yoga indicates a business archetype where wealth is extracted from conflict, enemies, or litigation. It suggests a career managing the debts, legal disputes, or failures of others.",
            "mode": "litigation_prone",
            "quality": "mixed",
            "confidence": 0.85,
        },
        "outputs": {
            "symbolic_label": "litigation_wealth_archetype",
            "likelihood_band": "moderate",
            "timing_band": "broad",
            "recommended_action": "leverage_conflict_resolution_skills",
        },
        "notes": "Archetypal indicator of litigation-based professions or businesses profiting from conflict and restructuring.",
    },
    {
        "rule_id": "nirayana_mars_sun_moon_partnership",
        "name": "Mars-Sun-Moon Combination — Partnership Business Wealth",
        "description": "Mars in combination with Sun and Moon (exalted or strong) gives wealth through business partnership.",
        "source_text": {
            "work_name": "Predictive Astrology Through The Nirayana System",
            "chapter": None,
            "verse": None,
            "page": "28",
            "quote": "Mars exalted or alone in combination with Sun and Moon gives wealth through marriage and business partnership;",
        },
        "domain": "business",
        "event_family": "business_partnership",
        "event_subtype": ["partnership_business"],
        "rule_type": "combination",
        "status": "active",
        "priority": 80,
        "polarity": "supportive",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "planet_conjunction", "operator": "conjunct", "value": {"planets": ["Mars", "Sun", "Moon"]}},
            ],
            "any_of": [
                {"kind": "planet_dignity", "operator": "is_exalted", "value": "Mars"},
                {"kind": "planet_dignity", "operator": "is_own_sign", "value": "Mars"},
            ],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": [],
            "planets": ["Mars", "Sun", "Moon"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.85,
        },
        "interpretation": {
            "meaning": "Symbolic indicator of wealth generation through strong alliances. Mars providing the energetic drive, harmonized with the luminaries, favors cooperative business partnerships.",
            "mode": "partnership_business",
            "quality": "supportive",
            "confidence": 0.80,
        },
        "outputs": {
            "symbolic_label": "partnership_wealth_archetype",
            "likelihood_band": "moderate",
            "timing_band": "broad",
            "recommended_action": "pursue_joint_ventures",
        },
        "notes": "An astrological archetype for successful joint ventures.",
    },
    {
        "rule_id": "nirayana_mercury_10th_import_export",
        "name": "Mercury Alone in 10th — Merchant & Export Business",
        "description": "Mercury independently in the career house is the classic signature of the merchant and trader: high-volume transactions, logistics, import/export.",
        "source_text": {
            "work_name": "Predictive Astrology Through The Nirayana System",
            "chapter": None,
            "verse": None,
            "page": "224",
            "quote": "If alone: Exporter, wholesaler, distributor or commission agent. In airy signs, Mercury in 10 gives fluent speech for business activities.",
        },
        "domain": "business",
        "event_family": "scaling",
        "event_subtype": ["import_export", "scalable_business"],
        "rule_type": "house_activation",
        "status": "active",
        "priority": 88,
        "polarity": "supportive",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "planet_in_house", "operator": "in", "value": [10]},
            ],
            "any_of": [],
            "none_of": [
                {"kind": "planet_conjunction", "operator": "conjunct", "value": "any_planet"},
            ],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["10"],
            "planets": ["Mercury"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.90,
        },
        "interpretation": {
            "meaning": "Mercury situated independently in the career house is the classic signature of the merchant and trader. It signifies high-volume transactions, logistics, import/export, and commission-based scalable businesses.",
            "mode": "import_export",
            "quality": "supportive",
            "confidence": 0.90,
        },
        "outputs": {
            "symbolic_label": "merchant_trader_archetype",
            "likelihood_band": "high",
            "timing_band": "broad",
            "recommended_action": "build_scalable_commercial_operations",
        },
        "notes": "If Mercury is in an airy sign (Gemini, Libra, Aquarius), it adds advanced fluency and public relations skills.",
    },
    {
        "rule_id": "jataka_parijata_mars_navamsa_technology",
        "name": "Mars Navamsa — Technology & Engineering Business",
        "description": "When the livelihood Navamsa is ruled by Mars (Aries/Scorpio), it creates the archetype for technical businesses involving fire, machinery, or engineering.",
        "source_text": {
            "work_name": "Jataka Parijata",
            "chapter": "15",
            "verse": "46-47",
            "page": None,
            "quote": "If the Navamsa in question belong to Mars, the person gains a livelihood by metallurgy, by working in fire... and by engaging in other people's quarrels, in any act of daring",
        },
        "domain": "business",
        "event_family": "business_launch",
        "event_subtype": ["technology_business", "litigation_prone"],
        "rule_type": "d9",
        "status": "active",
        "priority": 82,
        "polarity": "mixed",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "navamsa_lord", "operator": "equals", "value": "Mars"},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["10"],
            "planets": ["Mars"],
            "nakshatra": [],
            "d9": ["Mars_Navamsa"],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.90,
        },
        "interpretation": {
            "meaning": "Archetypal signature for technical businesses involving fire, machinery, engineering (metallurgy), or confrontational arenas such as legal disputes and risk-heavy daring ventures.",
            "mode": "technology_business",
            "quality": "mixed",
            "confidence": 0.85,
        },
        "outputs": {
            "symbolic_label": "technology_engineering_archetype",
            "likelihood_band": "moderate",
            "timing_band": "broad",
            "recommended_action": "align_with_technical_ventures",
        },
        "notes": "In a modern context, working with 'fire and metallurgy' translates to technology, heavy industry, and engineering.",
    },
    {
        "rule_id": "nirayana_5th_8th_parivartana",
        "name": "5th-8th Parivartana — Large-Scale Market Investments",
        "description": "The exchange between the house of speculation (5th) and hidden wealth/OPM (8th) creates a potent archetype for massive success in market investments.",
        "source_text": {
            "work_name": "Predictive Astrology Through The Nirayana System",
            "chapter": None,
            "verse": None,
            "page": "204",
            "quote": "A person will do well in large-scale market investments when their 8th lord is well placed and aspected; when their 5th lord is well-placed and well-aspected; and, ideally, if these two lords enjoy parivartan.",
        },
        "domain": "business",
        "event_family": "speculative_business",
        "event_subtype": ["speculative_business", "sudden_gains"],
        "rule_type": "yoga",
        "status": "active",
        "priority": 88,
        "polarity": "supportive",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "planet_dignity", "operator": "is_strong", "value": "8th_lord"},
                {"kind": "planet_dignity", "operator": "is_strong", "value": "5th_lord"},
                {"kind": "parivartana", "operator": "has_exchange", "value": {"houses": [5, 8]}},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["5", "8"],
            "planets": ["5th_lord", "8th_lord"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.90,
        },
        "interpretation": {
            "meaning": "The exchange between the house of speculation and creative intelligence (5th) and the house of other people's money, hidden wealth, and market fluctuations (8th) creates a highly favorable archetype for large-scale market investments and sudden speculative windfalls.",
            "mode": "speculative_business",
            "quality": "supportive",
            "confidence": 0.95,
        },
        "outputs": {
            "symbolic_label": "speculative_investment_archetype",
            "likelihood_band": "high",
            "timing_band": "broad",
            "recommended_action": "deploy_capital_in_markets",
        },
        "notes": "Connects collective financial currents (8th) with personal speculative instinct (5th).",
    },
    {
        "rule_id": "nirayana_chandra_mangala_11th_viral",
        "name": "Chandra-Mangala Yoga in 11th — Viral/Network Business",
        "description": "Moon-Mars conjunction in the 11th house yields immense popularity, viral reach, and profitable scaling through marketplace communities.",
        "source_text": {
            "work_name": "Predictive Astrology Through The Nirayana System",
            "chapter": None,
            "verse": None,
            "page": "172",
            "quote": "Chandra-Mangala yoga here gives financial benefit here in nearly any rashi. Special dignity and added income for business in marketplace activities, buy-sell, community development, interconnections between linked networks of association.",
        },
        "domain": "business",
        "event_family": "scaling",
        "event_subtype": ["viral_public_popularity", "scalable_business"],
        "rule_type": "yoga",
        "status": "active",
        "priority": 88,
        "polarity": "supportive",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "planet_conjunction", "operator": "conjunct", "value": {"planets": ["Moon", "Mars"]}},
                {"kind": "planet_in_house", "operator": "in", "value": [11]},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["11"],
            "planets": ["Moon", "Mars"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.90,
        },
        "interpretation": {
            "meaning": "The highly energized connection of mind/public (Moon) and ambition (Mars) in the house of networks (11th) yields immense popularity, viral reach, and highly profitable scaling through marketplace communities.",
            "mode": "scalable_business",
            "quality": "supportive",
            "confidence": 0.90,
        },
        "outputs": {
            "symbolic_label": "viral_network_business_archetype",
            "likelihood_band": "high",
            "timing_band": "broad",
            "recommended_action": "scale_through_community_networks",
        },
        "notes": "Classic indicator for modern social network-driven business success.",
    },
    {
        "rule_id": "nirayana_venus_7th_luxury_partnership",
        "name": "Venus in 7th (Strong) — Luxury & Partnership Business",
        "description": "Venus strong in the 7th house symbolizes business success through high-end trade, aesthetics, luxury goods, and balanced partnerships.",
        "source_text": {
            "work_name": "Predictive Astrology Through The Nirayana System",
            "chapter": None,
            "verse": None,
            "page": "72",
            "quote": "When Shukra is strong in yuvati sthana... In business, good for trading in women's articles, wine, luxury goods. Also good for having a female business partner",
        },
        "domain": "business",
        "event_family": "business_partnership",
        "event_subtype": ["partnership_business", "scalable_business"],
        "rule_type": "house_activation",
        "status": "active",
        "priority": 82,
        "polarity": "supportive",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "planet_in_house", "operator": "in", "value": [7]},
                {"kind": "planet_dignity", "operator": "is_strong", "value": "Venus"},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["7"],
            "planets": ["Venus"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.85,
        },
        "interpretation": {
            "meaning": "Symbolizes a business archetype rooted in high-end trade, aesthetics, luxury goods, and balanced commercial partnerships. Excellent for leveraging charm and design in commerce.",
            "mode": "partnership_business",
            "quality": "supportive",
            "confidence": 0.85,
        },
        "outputs": {
            "symbolic_label": "luxury_partnership_archetype",
            "likelihood_band": "moderate",
            "timing_band": "broad",
            "recommended_action": "build_aesthetic_brand_partnerships",
        },
        "notes": "Indicates smooth diplomatic ties with partners, though the 'too much of a good thing' principle can make the business overly focused on pleasure rather than strict discipline.",
    },
    {
        "rule_id": "nirayana_moon_2nd_family_business",
        "name": "Moon in 2nd — Family Business Archetype",
        "description": "Moon in the 2nd house creates a powerful psychological attachment to family wealth, tradition, and taking up the mantle of a family business.",
        "source_text": {
            "work_name": "Predictive Astrology Through The Nirayana System",
            "chapter": None,
            "verse": None,
            "page": "185",
            "quote": "Needs to see oneself as a bearer of traditional ethnic values esp. of art, song, ancient knowledge, wealth and beauty... Identifies strongly with the family business, or a service lineage descending through the family.",
        },
        "domain": "business",
        "event_family": "business_launch",
        "event_subtype": ["family_business"],
        "rule_type": "house_activation",
        "status": "active",
        "priority": 78,
        "polarity": "supportive",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "planet_in_house", "operator": "in", "value": [2]},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["2"],
            "planets": ["Moon"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.85,
        },
        "interpretation": {
            "meaning": "The emotional mind (Moon) grounded in the house of lineage and accumulated assets (2nd) creates a powerful psychological attachment to family wealth, tradition, and taking up the mantle of a family business.",
            "mode": "family_business",
            "quality": "supportive",
            "confidence": 0.85,
        },
        "outputs": {
            "symbolic_label": "family_business_archetype",
            "likelihood_band": "moderate",
            "timing_band": "broad",
            "recommended_action": "honor_legacy_and_expand",
        },
        "notes": "Indicates wealth preservation over generations.",
    },
    {
        "rule_id": "nirayana_chandra_mangala_7th_litigation",
        "name": "Chandra-Mangala Yoga in 7th — Contract & Litigation Business",
        "description": "Moon-Mars conjunction in 7th generates profit through constantly re-negotiated agreements, legal challenges, and high-friction contracts.",
        "source_text": {
            "work_name": "Predictive Astrology Through The Nirayana System",
            "chapter": None,
            "verse": None,
            "page": "172",
            "quote": "Chandra-Mangala yoga here gives financial benefit through making agreements which have to be re-negotiated frequently. Good for attorney or litigator.",
        },
        "domain": "business",
        "event_family": "business_partnership",
        "event_subtype": ["partnership_business", "litigation_prone"],
        "rule_type": "yoga",
        "status": "active",
        "priority": 82,
        "polarity": "mixed",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "planet_conjunction", "operator": "conjunct", "value": {"planets": ["Moon", "Mars"]}},
                {"kind": "planet_in_house", "operator": "in", "value": [7]},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["7"],
            "planets": ["Moon", "Mars"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.85,
        },
        "interpretation": {
            "meaning": "The volatile combination of emotions (Moon) and aggression (Mars) in the house of contracts (7th) generates profit but ensures business partnerships are intensely debated, legally challenged, and constantly re-negotiated.",
            "mode": "partnership_business",
            "quality": "conflict_prone",
            "confidence": 0.85,
        },
        "outputs": {
            "symbolic_label": "litigation_partnership_archetype",
            "likelihood_band": "moderate",
            "timing_band": "broad",
            "recommended_action": "manage_high_friction_contracts",
        },
        "notes": "Highly profitable for attorneys, agents, and those managing high-friction contracts.",
    },
    {
        "rule_id": "nirayana_lagnesha_in_3rd",
        "name": "Lagnesha in 3rd — Born Business Administrator",
        "description": "When the ruler of the self (1st) is placed in the house of commerce and self-effort (3rd), it creates a natural business administrator.",
        "source_text": {
            "work_name": "Predictive Astrology Through The Nirayana System",
            "chapter": None,
            "verse": None,
            "page": "193",
            "quote": "Lagnesha in domain-3 = Personality controls the daily business. Native is a born business administrator, with natural talents in all commercial behaviors such as sales, marketing, public relations, advertising, planning & execution.",
        },
        "domain": "business",
        "event_family": "scaling",
        "event_subtype": ["scalable_business"],
        "rule_type": "house_activation",
        "status": "active",
        "priority": 88,
        "polarity": "supportive",
        "timing_band": "none",
        "conditions": {
            "all_of": [
                {"kind": "house_lord_position", "operator": "in", "value": {"lord_of": 1, "in_house": 3}},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": ["1", "3"],
            "planets": ["1st_lord"],
            "nakshatra": [],
            "d9": [],
            "sensitive_points": [],
        },
        "window": None,
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.0,
            "classical_weight": 0.90,
        },
        "interpretation": {
            "meaning": "When the ruler of the self (1st) is placed in the house of commerce and self-effort (3rd), it creates a natural business administrator. The native thrives in sales, marketing, public relations, and detail-oriented commercial execution.",
            "mode": "scalable_business",
            "quality": "supportive",
            "confidence": 0.90,
        },
        "outputs": {
            "symbolic_label": "born_administrator_archetype",
            "likelihood_band": "high",
            "timing_band": "broad",
            "recommended_action": "lead_commercial_operations",
        },
        "notes": "The 3rd house is 2nd-from-2nd, indicating self-made wealth. An exalted planet here makes a true captain of industry.",
    },
]
