"""
Business Domain — Fast Trigger Rules (Layer: Exact Timing)

These rules fire on exact-day events: Moon transits through specific Nakshatras,
Mars hitting sensitive points, Navamsa counts, etc.
They narrow the active transit window into a TARGET DAY.

Sources: Phaladeepika, Saravatobhadra Chakra, Jataka Parijata, Nakshatra research
"""

FAST_TRIGGER_RULES = [
    {
        "rule_id": "fast_trigger_sanghatika_business_crisis",
        "name": "Sanghatika (16th Star) — Sudden Business Crisis Trigger",
        "description": "Activation of the 16th Nakshatra from the natal Moon acts as a catalyst for sudden business crises, financial liabilities, and structural professional disputes.",
        "source_text": {
            "work_name": "Nakshatras as Celestial Blueprints",
            "chapter": None,
            "verse": None,
            "page": None,
            "quote": "Sanghatika 16th Star... Triggers financial liabilities, disputes, and structural or business crises.",
        },
        "domain": "business",
        "event_family": "business_closure",
        "event_subtype": ["sudden_business_reversals"],
        "rule_type": "fast_trigger",
        "status": "active",
        "priority": 92,
        "polarity": "challenging",
        "timing_band": "exact",
        "conditions": {
            "all_of": [
                {"kind": "nakshatra_from_moon", "operator": "equals", "value": 16},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": ["Malefics"],
            "houses": [],
            "planets": [],
            "nakshatra": ["16th_from_Moon"],
            "d9": [],
            "sensitive_points": ["Sanghatika_Nakshatra"],
        },
        "window": {
            "broad_window_days": 3,
            "exact_window_days": 1,
            "confidence_decay_days": 2,
        },
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 1.0,
            "classical_weight": 0.0,
        },
        "interpretation": {
            "meaning": "Provides an exact longitude-sensitive trigger. Activation of the 16th star from the natal Moon acts as a catalyst for sudden business crises, financial liabilities, and structural professional disputes.",
            "mode": "unknown",
            "quality": "conflict_prone",
            "confidence": 0.90,
        },
        "outputs": {
            "symbolic_label": "sanghatika_crisis_trigger",
            "likelihood_band": "high",
            "timing_band": "exact",
            "recommended_action": "protect_and_defer_decisions",
        },
        "notes": "Highly precise timing method for pinpointing the exact days of sudden business disruptions or forced restructuring.",
    },
    {
        "rule_id": "fast_trigger_navatara_mitra_funding",
        "name": "Mitra Tara (8th Nakshatra) — Partnership & Funding Trigger",
        "description": "The Moon's transit through the 8th Nakshatra (Mitra Tara) triggers fast, supportive financial gains through partnerships or funding.",
        "source_text": {
            "work_name": "45 SARAVATOBHADRA CHAKRA IN ASTROLOGY",
            "chapter": None,
            "verse": None,
            "page": None,
            "quote": "8th Nakshatra Mitra Financial gain & Success through friend",
        },
        "domain": "business",
        "event_family": "funding",
        "event_subtype": ["funding_events", "partnership_signing", "major_sales_spikes"],
        "rule_type": "fast_trigger",
        "status": "active",
        "priority": 88,
        "polarity": "supportive",
        "timing_band": "exact",
        "conditions": {
            "all_of": [
                {"kind": "nakshatra_from_moon", "operator": "equals", "value": 8},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": ["Moon"],
            "houses": [],
            "planets": [],
            "nakshatra": ["8th_from_Moon"],
            "d9": [],
            "sensitive_points": ["Mitra_Tara"],
        },
        "window": {
            "broad_window_days": 2,
            "exact_window_days": 1,
            "confidence_decay_days": 1,
        },
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.85,
            "classical_weight": 0.0,
        },
        "interpretation": {
            "meaning": "The exact transit of the Moon through the 8th Nakshatra from the birth star triggers fast, supportive financial gains, often manifesting through business partnerships, networking, or the acquisition of funding from allies.",
            "mode": "unknown",
            "quality": "supportive",
            "confidence": 0.85,
        },
        "outputs": {
            "symbolic_label": "mitra_tara_funding_trigger",
            "likelihood_band": "high",
            "timing_band": "exact",
            "recommended_action": "sign_partnerships_close_deals",
        },
        "notes": "An application of Navatara (Tara Bala) used for selecting the exact day to sign a partnership deal or close a funding round.",
    },
    {
        "rule_id": "fast_trigger_navatara_param_mitra_gains",
        "name": "Param Mitra Tara (9th Nakshatra) — Intimate Partner Gains",
        "description": "The Moon's transit through the 9th Nakshatra (Param Mitra) triggers immediate financial success through trusted partners or co-founders.",
        "source_text": {
            "work_name": "45 SARAVATOBHADRA CHAKRA IN ASTROLOGY",
            "chapter": None,
            "verse": None,
            "page": None,
            "quote": "9th Nakshatra Param Mitra Financial gain & Success through very intimate friend",
        },
        "domain": "business",
        "event_family": "business_partnership",
        "event_subtype": ["partnership_signing", "funding_events", "major_sales_spikes"],
        "rule_type": "fast_trigger",
        "status": "active",
        "priority": 88,
        "polarity": "supportive",
        "timing_band": "exact",
        "conditions": {
            "all_of": [
                {"kind": "nakshatra_from_moon", "operator": "equals", "value": 9},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": ["Moon"],
            "houses": [],
            "planets": [],
            "nakshatra": ["9th_from_Moon"],
            "d9": [],
            "sensitive_points": ["Param_Mitra_Tara"],
        },
        "window": {
            "broad_window_days": 2,
            "exact_window_days": 1,
            "confidence_decay_days": 1,
        },
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.85,
            "classical_weight": 0.0,
        },
        "interpretation": {
            "meaning": "The Moon's transit through the 9th Nakshatra (Param Mitra) triggers immediate financial success and business gains, particularly facilitated by highly trusted business partners, co-founders, or close investors.",
            "mode": "unknown",
            "quality": "supportive",
            "confidence": 0.85,
        },
        "outputs": {
            "symbolic_label": "param_mitra_partnership_trigger",
            "likelihood_band": "high",
            "timing_band": "exact",
            "recommended_action": "close_critical_agreements",
        },
        "notes": "Provides a highly auspicious daily timing trigger for closing crucial business agreements.",
    },
    {
        "rule_id": "fast_trigger_moon_transit_eyes_wealth",
        "name": "Moon Transit 9th-10th Nakshatra (Eyes) — Sudden Wealth Gain",
        "description": "When the Moon transits the 9th and 10th Nakshatras from birth star, it acts as a micro-trigger for immediate, sudden gains of wealth and sales.",
        "source_text": {
            "work_name": "MANTRESWARA'S PHALA DEEPIKA",
            "chapter": None,
            "verse": "36",
            "page": None,
            "quote": "The Moons's transit Distribution amongst limbs Effects... (d) 9th. 10th - two eyes gain of wealth",
        },
        "domain": "business",
        "event_family": "profit_growth",
        "event_subtype": ["sudden_gain", "major_sales_spikes"],
        "rule_type": "fast_trigger",
        "status": "active",
        "priority": 82,
        "polarity": "supportive",
        "timing_band": "exact",
        "conditions": {
            "all_of": [
                {"kind": "nakshatra_from_moon", "operator": "in", "value": [9, 10]},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": ["Moon"],
            "houses": [],
            "planets": [],
            "nakshatra": ["9th_from_Moon", "10th_from_Moon"],
            "d9": [],
            "sensitive_points": [],
        },
        "window": {
            "broad_window_days": 2,
            "exact_window_days": 1,
            "confidence_decay_days": 1,
        },
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.90,
            "classical_weight": 0.0,
        },
        "interpretation": {
            "meaning": "A fast micro-transit technique mapping Nakshatras to body parts. When the Moon transits the stars representing the eyes (9th and 10th from birth star), it acts as a micro-trigger for immediate, sudden gains of wealth and sales.",
            "mode": "unknown",
            "quality": "supportive",
            "confidence": 0.80,
        },
        "outputs": {
            "symbolic_label": "moon_eyes_wealth_trigger",
            "likelihood_band": "moderate",
            "timing_band": "exact",
            "recommended_action": "finalize_revenue_actions",
        },
        "notes": "Used in traditional panchang and muhurta to time the exact day a business payout or sale will be realized.",
    },
    {
        "rule_id": "fast_trigger_moon_transit_right_hand_acquisition",
        "name": "Moon Transit 25th-27th Nakshatra (Right Hand) — Wealth Acquisition",
        "description": "When the Moon activates the 25th-27th Nakshatras (right hand), it triggers physically acquiring wealth or finalizing deals.",
        "source_text": {
            "work_name": "MANTRESWARA'S PHALA DEEPIKA",
            "chapter": None,
            "verse": "36",
            "page": None,
            "quote": "The Moons's transit Distribution amongst limbs Effects... (h) 25th. 26th. 27th - right hand acquisition of wealth",
        },
        "domain": "business",
        "event_family": "profit_growth",
        "event_subtype": ["deal_signing", "speculative_gains", "sudden_gain"],
        "rule_type": "fast_trigger",
        "status": "active",
        "priority": 85,
        "polarity": "supportive",
        "timing_band": "exact",
        "conditions": {
            "all_of": [
                {"kind": "nakshatra_from_moon", "operator": "in", "value": [25, 26, 27]},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": ["Moon"],
            "houses": [],
            "planets": [],
            "nakshatra": ["25th_from_Moon", "26th_from_Moon", "27th_from_Moon"],
            "d9": [],
            "sensitive_points": [],
        },
        "window": {
            "broad_window_days": 3,
            "exact_window_days": 1,
            "confidence_decay_days": 1,
        },
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.90,
            "classical_weight": 0.0,
        },
        "interpretation": {
            "meaning": "When the Moon activates the final trine of Nakshatras associated with the right hand (the hand of receiving), it serves as a highly accurate fast trigger for physically acquiring wealth, finalizing a lucrative deal, or taking profits.",
            "mode": "unknown",
            "quality": "supportive",
            "confidence": 0.85,
        },
        "outputs": {
            "symbolic_label": "right_hand_acquisition_trigger",
            "likelihood_band": "high",
            "timing_band": "exact",
            "recommended_action": "sign_contracts_receive_payments",
        },
        "notes": "Represents the physical act of receiving funds or signing documents on specific days of the lunar month.",
    },
    {
        "rule_id": "fast_trigger_mars_transit_head_gains",
        "name": "Mars Transit 16th-17th Nakshatra (Head) — Aggressive Gains",
        "description": "Mars transiting the 16th or 17th Nakshatra from the birth star ignites sudden gains, rapid profit taking, and sharp sales spikes.",
        "source_text": {
            "work_name": "MANTRESWARA'S PHALA DEEPIKA",
            "chapter": None,
            "verse": "37-38",
            "page": None,
            "quote": "Mars' transit Distribution amongst limbs Effects... (e) 16th. 17th - head gains",
        },
        "domain": "business",
        "event_family": "profit_growth",
        "event_subtype": ["sudden_gain", "speculative_gains", "major_sales_spikes"],
        "rule_type": "fast_trigger",
        "status": "active",
        "priority": 82,
        "polarity": "supportive",
        "timing_band": "exact",
        "conditions": {
            "all_of": [
                {"kind": "nakshatra_from_moon", "operator": "in", "value": [16, 17]},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": ["Mars"],
            "houses": [],
            "planets": [],
            "nakshatra": ["16th_from_Moon", "17th_from_Moon"],
            "d9": [],
            "sensitive_points": [],
        },
        "window": {
            "broad_window_days": 14,
            "exact_window_days": 5,
            "confidence_decay_days": 3,
        },
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 0.85,
            "classical_weight": 0.0,
        },
        "interpretation": {
            "meaning": "Mars serves as a dynamic trigger for fast, aggressive action. When it transits the 16th or 17th Nakshatra from the birth star, it ignites sudden gains, rapid profit taking, and sharp sales spikes in business operations.",
            "mode": "unknown",
            "quality": "supportive",
            "confidence": 0.80,
        },
        "outputs": {
            "symbolic_label": "mars_head_gains_trigger",
            "likelihood_band": "moderate",
            "timing_band": "exact",
            "recommended_action": "execute_aggressive_sales",
        },
        "notes": "Since Mars takes roughly 1.5 to 2 months to cross a sign, its transit over a specific Nakshatra gives an exact 2-3 week window for intense financial action.",
    },
    {
        "rule_id": "exact_timing_business_completion_navamsa_count",
        "name": "Navamsa Count — Exact Day of Business Completion",
        "description": "An exact mathematical timing methodology where the Navamsa distance between Ascendant and business significator equals the number of days until the deal completes.",
        "source_text": {
            "work_name": "Jataka Parijata",
            "chapter": "Vol 1",
            "verse": None,
            "page": None,
            "quote": "According to the first view, Vrischika Navamsa being the 2nd in the Mithuna lagna, the completion or success of the business has to be predicted to happen in 2 days.",
        },
        "domain": "business",
        "event_family": "business_launch",
        "event_subtype": ["deal_signing", "company_launch"],
        "rule_type": "fast_trigger",
        "status": "active",
        "priority": 80,
        "polarity": "supportive",
        "timing_band": "exact",
        "conditions": {
            "all_of": [
                {"kind": "navamsa_house", "operator": "in", "value": "count_from_lagna_to_significator"},
            ],
            "any_of": [],
            "none_of": [],
        },
        "signals": {
            "dasha": [],
            "transit": [],
            "houses": [],
            "planets": ["Business_Significator"],
            "nakshatra": [],
            "d9": ["Significator_Navamsa", "Lagna_Navamsa"],
            "sensitive_points": [],
        },
        "window": {
            "broad_window_days": 9,
            "exact_window_days": 1,
            "confidence_decay_days": 2,
        },
        "weights": {
            "dasha_weight": 0.0,
            "transit_weight": 0.0,
            "fast_trigger_weight": 1.0,
            "classical_weight": 0.0,
        },
        "interpretation": {
            "meaning": "An exact mathematical timing methodology where the spatial distance (measured in Navamsa divisions) between the Ascendant and the business's ruling planet equals the exact number of days until the business deal completes or succeeds.",
            "mode": "unknown",
            "quality": "supportive",
            "confidence": 0.85,
        },
        "outputs": {
            "symbolic_label": "navamsa_count_exact_day",
            "likelihood_band": "high",
            "timing_band": "exact",
            "recommended_action": "target_specific_day",
        },
        "notes": "Used heavily in Prashna (Horary) astrology to give exact day counts for the execution, signing, or launch of a business venture.",
    },
]
